
version: '3.7'

networks:
  backend:

services:
  php:
    build: docker/php
    container_name: php_jenkins
    networks:
      - backend
    environment:
      - COMPOSER_MEMORY_LIMIT=2G
      - XDEBUG_SESSION="PHPSTORM"
    volumes:
      - ./:/var/www/allximik
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  postgres:
    image: postgres:latest
    networks:
      - backend
    ports:
      # AMQP protocol port
      - '5436:5432'
    environment:
      POSTGRES_DB: "allximik"
      POSTGRES_USER: "allximik"
      POSTGRES_PASSWORD: "FWo123"
      PGDATA: "/var/lib/postgresql/data/pgdata"

  redis:
    image: bitnami/redis:latest
    networks:
      - backend
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
