networks:
  frontend:
    external: true
  backend:

services:
  nginx:
    build: ./docker/nginx
    container_name: nginx_allximik
    volumes:
      - ./docker/logs/nginx:/var/log/nginx
      - .:/var/www/allximik
    environment:
      - VIRTUAL_HOST=allximik.test
    ports:
      - "80:80"
    networks:
      frontend:
      backend:
        aliases:
          - allximik.test

  php:
    build: ./docker/php
    container_name: php_allximik
    networks:
      - backend
    environment:
      - COMPOSER_MEMORY_LIMIT=2G
      - XDEBUG_SESSION="PHPSTORM"
    volumes:
      - .:/var/www/allximik
      - ./storage/logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  postgres:
    image: postgres:latest
    networks:
      frontend:
      backend:
    ports:
      - '5437:5432'
    environment:
      POSTGRES_DB: allximik
      POSTGRES_USER: allximik
      POSTGRES_PASSWORD: allximik
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/postgres/allximik:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:latest
    networks:
      - backend
      - frontend
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  supervisor:
      build: ./docker/supervisor
      container_name: supervisor_allximik
      networks:
          - backend
      volumes:
          - .:/var/www/allximik
          - ./storage/logs:/var/log/php
          - ./docker/php/php.ini:/usr/local/etc/php/php.ini
          - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini

  rabbitmq:
      image: rabbitmq:3-management-alpine
      ports:
          # AMQP protocol port
          - '5679:5672'
          # HTTP management UI
          - '15679:15672'
      volumes:
          - ./docker/rabbitmq/data/:/var/lib/rabbitmq/
      networks:
          - backend
